language: elixir
elixir:
    - 1.4
    - 1.5
    - 1.6
otp_release:
    - 19.3
    - 20.3

env:
  global:
    - MIX_ENV=test

matrix:
  exclude:
    - elixir: 1.3.4
      otp_release: 20.2.4


sudo: false

script:
  - mix test
  - mix credo
  - mix coveralls.travis